_wandb:
    value:
        cli_version: 0.21.1
        e:
            lixap78m3qs7rx24pzx4ztf6hmp546gi:
                codePath: Lab1-CNNs.ipynb
                codePathLocal: Lab1-CNNs.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "1021821579264"
                        used: "807866363904"
                email: lorictongo19@gmail.com
                executable: c:\Users\loric\OneDrive\Documents\LM_IA_Unifi\Anaconda3\python.exe
                gpu: NVIDIA GeForce RTX 3050 6GB Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2560
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3050 6GB Laptop GPU
                      uuid: GPU-29aefb43-eb0b-a2cd-ae3f-d4058d477095
                host: Loric
                memory:
                    total: "14702026752"
                os: Windows-11-10.0.26200-SP0
                program: c:\Users\loric\OneDrive\Documents\LM_IA_Unifi\Laboratori\DeepLearningApplication\Lab1\Lab1-CNNs.ipynb
                python: CPython 3.12.3
                root: c:\Users\loric\OneDrive\Documents\LM_IA_Unifi\Laboratori\DeepLearningApplication\Lab1
                startedAt: "2025-12-15T11:04:37.482247Z"
                writerId: lixap78m3qs7rx24pzx4ztf6hmp546gi
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 13
            "4": 3.12.3
            "5": 0.21.1
            "8":
                - 1
                - 3
            "10":
                - 20
            "12": 0.21.1
            "13": windows-amd64
